/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MIMX8MM6xxxLZ
package_id: MIMX8MM6DVTLZ
mcu_data: ksdk2_0
processor_version: 25.09.10
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'false', coreID: a53_0}
- pin_list:
  - {pin_num: AG19, peripheral: SAI6, signal: sai_tx_sync, pin_signal: SAI1_RXD6}
  - {pin_num: AG18, peripheral: SAI6, signal: sai_tx_bclk, pin_signal: SAI1_RXD4}
  - {pin_num: AF18, peripheral: SAI6, signal: 'sai_tx_data, 0', pin_signal: SAI1_RXD5}
  - {pin_num: AF22, peripheral: SAI6, signal: 'sai_rx_data, 0', pin_signal: SAI1_TXD5}
  - {pin_num: AG21, peripheral: GPIO4, signal: 'gpio_io, 14', pin_signal: SAI1_TXD2}
  - {pin_num: AD6, peripheral: SAI3, signal: sai_mclk, pin_signal: SAI3_MCLK}
  - {pin_num: AG6, peripheral: SAI3, signal: sai_tx_bclk, pin_signal: SAI3_TXC}
  - {pin_num: AC6, peripheral: SAI3, signal: sai_tx_sync, pin_signal: SAI3_TXFS}
  - {pin_num: AF6, peripheral: SAI3, signal: 'sai_tx_data, 0', pin_signal: SAI3_TXD}
  - {pin_num: AF7, peripheral: SAI3, signal: 'sai_rx_data, 0', pin_signal: SAI3_RXD}
  - {pin_num: AG9, peripheral: GPIO5, signal: 'gpio_io, 04', pin_signal: SPDIF_RX}
  - {pin_num: AF8, peripheral: GPIO5, signal: 'gpio_io, 05', pin_signal: SPDIF_EXT_CLK}
  - {pin_num: AC14, peripheral: SAI5, signal: sai_tx_sync, pin_signal: SAI5_RXD1}
  - {pin_num: AC15, peripheral: SAI5, signal: sai_rx_bclk, pin_signal: SAI5_RXC}
  - {pin_num: AC13, peripheral: SAI5, signal: 'sai_tx_data, 0', pin_signal: SAI5_RXD3}
  - {pin_num: AD18, peripheral: SAI5, signal: 'sai_rx_data, 0', pin_signal: SAI5_RXD0}
  - {pin_num: AG23, peripheral: GPIO4, signal: 'gpio_io, 18', pin_signal: SAI1_TXD6}
  - {pin_num: AB18, peripheral: SAI1, signal: sai_mclk, pin_signal: SAI1_MCLK}
  - {pin_num: AB19, peripheral: SAI1, signal: sai_tx_sync, pin_signal: SAI1_TXFS}
  - {pin_num: AC18, peripheral: SAI1, signal: sai_tx_bclk, pin_signal: SAI1_TXC}
  - {pin_num: AG20, peripheral: SAI1, signal: 'sai_tx_data, 0', pin_signal: SAI1_TXD0}
  - {pin_num: AF20, peripheral: SAI1, signal: 'sai_tx_data, 1', pin_signal: SAI1_TXD1}
  - {pin_num: AD10, peripheral: GPIO1, signal: 'gpio_io, 10', pin_signal: GPIO1_IO10}
  - {pin_num: AC10, peripheral: GPIO1, signal: 'gpio_io, 11', pin_signal: GPIO1_IO11}
  - {pin_num: AB10, peripheral: GPIO1, signal: 'gpio_io, 12', pin_signal: GPIO1_IO12}
  - {pin_num: AD9, peripheral: GPIO1, signal: 'gpio_io, 13', pin_signal: GPIO1_IO13}
  - {pin_num: AF19, peripheral: GPIO4, signal: 'gpio_io, 09', pin_signal: SAI1_RXD7}
  - {pin_num: E6, peripheral: ECSPI2, signal: ecspi_sclk, pin_signal: ECSPI2_SCLK}
  - {pin_num: A8, peripheral: ECSPI2, signal: ecspi_miso, pin_signal: ECSPI2_MISO}
  - {pin_num: B8, peripheral: ECSPI2, signal: ecspi_mosi, pin_signal: ECSPI2_MOSI}
  - {pin_num: A6, peripheral: ECSPI2, signal: 'ecspi_ss, 0', pin_signal: ECSPI2_SS0}
  - {pin_num: AF21, peripheral: GPIO4, signal: 'gpio_io, 15', pin_signal: SAI1_TXD3}
  - {pin_num: AG22, peripheral: GPIO4, signal: 'gpio_io, 16', pin_signal: SAI1_TXD4}
  - {pin_num: N24, peripheral: GPIO3, signal: 'gpio_io, 01', pin_signal: NAND_CE0_B}
  - {pin_num: W27, peripheral: GPIO2, signal: 'gpio_io, 08', pin_signal: SD1_DATA6}
  - {pin_num: AF9, peripheral: GPIO5, signal: 'gpio_io, 03', pin_signal: SPDIF_TX}
  - {pin_num: AG14, peripheral: GPIO1, signal: 'gpio_io, 00', pin_signal: GPIO1_IO00}
  - {pin_num: AF14, peripheral: GPIO1, signal: 'gpio_io, 01', pin_signal: GPIO1_IO01}
  - {pin_num: AG12, peripheral: GPIO1, signal: 'gpio_io, 04', pin_signal: GPIO1_IO04}
  - {pin_num: AF12, peripheral: GPIO1, signal: 'gpio_io, 05', pin_signal: GPIO1_IO05}
  - {pin_num: AG11, peripheral: GPIO1, signal: 'gpio_io, 06', pin_signal: GPIO1_IO06}
  - {pin_num: AF11, peripheral: GPIO1, signal: 'gpio_io, 07', pin_signal: GPIO1_IO07}
  - {pin_num: AG10, peripheral: GPIO1, signal: 'gpio_io, 08', pin_signal: GPIO1_IO08}
  - {pin_num: AF10, peripheral: GPIO1, signal: 'gpio_io, 09', pin_signal: GPIO1_IO09}
  - {pin_num: AC27, peripheral: ENET1, signal: enet_mdc, pin_signal: ENET_MDC}
  - {pin_num: AB27, peripheral: ENET1, signal: enet_mdio, pin_signal: ENET_MDIO}
  - {pin_num: AF24, peripheral: ENET1, signal: enet_rgmii_tx_ctl, pin_signal: ENET_TX_CTL}
  - {pin_num: AG24, peripheral: ENET1, signal: enet_rgmii_txc, pin_signal: ENET_TXC}
  - {pin_num: AG26, peripheral: ENET1, signal: 'enet_rgmii_td, 0', pin_signal: ENET_TD0}
  - {pin_num: AF26, peripheral: ENET1, signal: 'enet_rgmii_td, 1', pin_signal: ENET_TD1}
  - {pin_num: AG25, peripheral: ENET1, signal: 'enet_rgmii_td, 2', pin_signal: ENET_TD2}
  - {pin_num: AF25, peripheral: ENET1, signal: 'enet_rgmii_td, 3', pin_signal: ENET_TD3}
  - {pin_num: AF27, peripheral: ENET1, signal: enet_rgmii_rx_ctl, pin_signal: ENET_RX_CTL}
  - {pin_num: AE26, peripheral: ENET1, signal: enet_rgmii_rxc, pin_signal: ENET_RXC}
  - {pin_num: AE27, peripheral: ENET1, signal: 'enet_rgmii_rd, 0', pin_signal: ENET_RD0}
  - {pin_num: AD27, peripheral: ENET1, signal: 'enet_rgmii_rd, 1', pin_signal: ENET_RD1}
  - {pin_num: AD26, peripheral: ENET1, signal: 'enet_rgmii_rd, 2', pin_signal: ENET_RD2}
  - {pin_num: AC26, peripheral: ENET1, signal: 'enet_rgmii_rd, 3', pin_signal: ENET_RD3}
  - {pin_num: AG17, peripheral: GPIO4, signal: 'gpio_io, 04', pin_signal: SAI1_RXD2}
  - {pin_num: AG16, peripheral: GPIO4, signal: 'gpio_io, 00', pin_signal: SAI1_RXFS}
  - {pin_num: AF16, peripheral: GPIO4, signal: 'gpio_io, 01', pin_signal: SAI1_RXC}
  - {pin_num: AG7, peripheral: GPIO4, signal: 'gpio_io, 29', pin_signal: SAI3_RXC}
  - {pin_num: R24, peripheral: GPIO2, signal: 'gpio_io, 11', pin_signal: SD1_STROBE}
  - {pin_num: U27, peripheral: GPIO2, signal: 'gpio_io, 06', pin_signal: SD1_DATA4}
  - {pin_num: AG8, peripheral: GPIO4, signal: 'gpio_io, 28', pin_signal: SAI3_RXFS}
  - {pin_num: F19, peripheral: UART4, signal: uart_rx, pin_signal: UART4_RXD}
  - {pin_num: F18, peripheral: UART4, signal: uart_tx, pin_signal: UART4_TXD}
  - {pin_num: AF17, peripheral: GPIO4, signal: 'gpio_io, 05', pin_signal: SAI1_RXD3}
  - {pin_num: V26, peripheral: uSDHC1, signal: usdhc_clk, pin_signal: SD1_CLK}
  - {pin_num: V27, peripheral: uSDHC1, signal: usdhc_cmd, pin_signal: SD1_CMD}
  - {pin_num: Y27, peripheral: uSDHC1, signal: 'usdhc_data, 0', pin_signal: SD1_DATA0}
  - {pin_num: Y26, peripheral: uSDHC1, signal: 'usdhc_data, 1', pin_signal: SD1_DATA1}
  - {pin_num: T27, peripheral: uSDHC1, signal: 'usdhc_data, 2', pin_signal: SD1_DATA2}
  - {pin_num: T26, peripheral: uSDHC1, signal: 'usdhc_data, 3', pin_signal: SD1_DATA3}
  - {pin_num: AB22, peripheral: GPIO4, signal: 'gpio_io, 22', pin_signal: SAI2_RXC}
  - {pin_num: D6, peripheral: ECSPI1, signal: ecspi_sclk, pin_signal: ECSPI1_SCLK}
  - {pin_num: A7, peripheral: ECSPI1, signal: ecspi_miso, pin_signal: ECSPI1_MISO}
  - {pin_num: B7, peripheral: ECSPI1, signal: ecspi_mosi, pin_signal: ECSPI1_MOSI}
  - {pin_num: B6, peripheral: ECSPI1, signal: 'ecspi_ss, 0', pin_signal: ECSPI1_SS0}
  - {pin_num: E14, peripheral: UART1, signal: uart_rx, pin_signal: UART1_RXD}
  - {pin_num: F13, peripheral: UART1, signal: uart_tx, pin_signal: UART1_TXD}
  - {pin_num: E18, peripheral: UART1, signal: uart_cts_b, pin_signal: UART3_RXD}
  - {pin_num: D18, peripheral: UART1, signal: uart_rts_b, pin_signal: UART3_TXD}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {                                /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_ECSPI1_MISO_ECSPI1_MISO, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI1_MOSI_ECSPI1_MOSI, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI1_SCLK_ECSPI1_SCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI1_SS0_ECSPI1_SS0, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI2_MISO_ECSPI2_MISO, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI2_MOSI_ECSPI2_MOSI, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI2_SCLK_ECSPI2_SCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI2_SS0_ECSPI2_SS0, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_MDC_ENET1_MDC, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_MDIO_ENET1_MDIO, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_RD0_ENET1_RGMII_RD0, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_RD1_ENET1_RGMII_RD1, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_RD2_ENET1_RGMII_RD2, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_RD3_ENET1_RGMII_RD3, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_RXC_ENET1_RGMII_RXC, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_RX_CTL_ENET1_RGMII_RX_CTL, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_TD0_ENET1_RGMII_TD0, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_TD1_ENET1_RGMII_TD1, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_TD2_ENET1_RGMII_TD2, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_TD3_ENET1_RGMII_TD3, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_TXC_ENET1_RGMII_TXC, 0U);
    IOMUXC_SetPinMux(IOMUXC_ENET_TX_CTL_ENET1_RGMII_TX_CTL, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO00_GPIO1_IO00, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO01_GPIO1_IO01, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO04_GPIO1_IO04, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO05_GPIO1_IO05, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO06_GPIO1_IO06, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO07_GPIO1_IO07, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO08_GPIO1_IO08, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO09_GPIO1_IO09, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO10_GPIO1_IO10, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO11_GPIO1_IO11, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO12_GPIO1_IO12, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO13_GPIO1_IO13, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_CE0_B_GPIO3_IO01, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_MCLK_SAI1_MCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXC_GPIO4_IO01, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXD2_GPIO4_IO04, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXD3_GPIO4_IO05, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXD4_SAI6_TX_BCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXD5_SAI6_TX_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXD6_SAI6_TX_SYNC, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXD7_GPIO4_IO09, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXFS_GPIO4_IO00, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXC_SAI1_TX_BCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD0_SAI1_TX_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD1_SAI1_TX_DATA1, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD2_GPIO4_IO14, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD3_GPIO4_IO15, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD4_GPIO4_IO16, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD5_SAI6_RX_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD6_GPIO4_IO18, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXFS_SAI1_TX_SYNC, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI2_RXC_GPIO4_IO22, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI3_MCLK_SAI3_MCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI3_RXC_GPIO4_IO29, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI3_RXD_SAI3_RX_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI3_RXFS_GPIO4_IO28, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI3_TXC_SAI3_TX_BCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI3_TXD_SAI3_TX_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI3_TXFS_SAI3_TX_SYNC, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI5_RXC_SAI5_RX_BCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI5_RXD0_SAI5_RX_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI5_RXD1_SAI5_TX_SYNC, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI5_RXD3_SAI5_TX_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_CLK_USDHC1_CLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_CMD_USDHC1_CMD, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA0_USDHC1_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA1_USDHC1_DATA1, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA2_USDHC1_DATA2, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA3_USDHC1_DATA3, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA4_GPIO2_IO06, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA6_GPIO2_IO08, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_STROBE_GPIO2_IO11, 0U);
    IOMUXC_SetPinMux(IOMUXC_SPDIF_EXT_CLK_GPIO5_IO05, 0U);
    IOMUXC_SetPinMux(IOMUXC_SPDIF_RX_GPIO5_IO04, 0U);
    IOMUXC_SetPinMux(IOMUXC_SPDIF_TX_GPIO5_IO03, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART1_RXD_UART1_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART1_TXD_UART1_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART3_RXD_UART1_CTS_B, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART3_TXD_UART1_RTS_B, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART4_RXD_UART4_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART4_TXD_UART4_TX, 0U);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
