blacklist snd_soc_tas2562
blacklist snd_soc_tas2563
blacklist snd_soc_tas2781_i2c
blacklist snd_soc_tas2781_comlib_i2c
blacklist snd_soc_tas2781_fmwlib
blacklist snd_soc_integrated_tasdevice
blacklist snd_soc_fsl_micfil
#blacklist snd_aloop
